//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""cd93eaba-4f5e-4d45-b152-9afee2c7b8cb"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2503a44e-de01-494d-a849-f819ab1103a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""93c06cbe-8f24-4b7d-acdb-eb72b4ed006e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""4f8bbe7d-fdff-4601-b38e-34a23a6800a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0ed6cbfe-8698-4dff-b5ff-5488d3e73074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""77623c41-5045-4db3-b681-679d417e986c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""59aa17fa-da05-41d5-8af2-ca2905f1fa8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast"",
                    ""type"": ""Button"",
                    ""id"": ""5992dc29-9da7-45d1-93e8-1e0d210bd619"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""a1fbe459-1d27-4f07-8ae7-d53aa7bcb832"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sheathe"",
                    ""type"": ""Button"",
                    ""id"": ""c67c5b77-43e4-46e4-8d05-84d3e7aa816c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""53bfa57f-666c-4d8d-bb52-513106024b55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipItem"",
                    ""type"": ""Button"",
                    ""id"": ""7578e0f1-ba30-466e-be08-644de1bb8668"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenItemInfo"",
                    ""type"": ""Button"",
                    ""id"": ""ed1d1c00-a786-453f-9ae9-7ef4db002a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""68001a43-ed66-493d-b10d-5846c1895701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""546779c5-a26c-4c1d-bdbb-5cee53d389ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3"",
                    ""type"": ""Button"",
                    ""id"": ""9e5a0bea-04f1-4427-a9cc-d497b8c4ff22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4"",
                    ""type"": ""Button"",
                    ""id"": ""14243c9e-4781-40da-a2a1-0eb5b99a6fe2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5"",
                    ""type"": ""Button"",
                    ""id"": ""f418368e-0932-4d91-a5db-d5ef4625e304"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6"",
                    ""type"": ""Button"",
                    ""id"": ""e4007ace-d404-4657-9bf6-d8c25bd4d52d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7"",
                    ""type"": ""Button"",
                    ""id"": ""4c1e8d38-f004-409b-92f5-b23d286e4661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8"",
                    ""type"": ""Button"",
                    ""id"": ""bce6554d-c22a-49dc-823c-85df5bd0ae81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9"",
                    ""type"": ""Button"",
                    ""id"": ""bf41153e-ab8b-469f-982e-4cadeb17fa31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectOptionNextDialog"",
                    ""type"": ""Button"",
                    ""id"": ""a5847640-7584-4685-b756-3cd97c44ba17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Repair"",
                    ""type"": ""Button"",
                    ""id"": ""b34ce2fe-1713-4629-bbd5-29f2ff90abcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""539dcec5-4f20-4996-91ff-715bb47a2fe5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9059d33e-7ecf-41d5-a8ea-8744eba9d733"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f1dd73ba-6f52-4832-9419-4953a83bbf83"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f1243b97-0d4e-43ef-8d3d-011de4b45aa8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ace151be-e29c-466f-b336-bd8c268e6808"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3ad306a0-9d9d-4cb8-8741-c2f4ccd1e35d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ebc543-b827-4e1e-9b72-02ac0fb5ac52"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08d4175c-c961-428f-99ec-1aa63f4ba34b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc20ae64-d349-43c4-a99d-b7044a921091"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0f1b98-1ffc-44f9-b6c2-05f55b851337"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93c5f42a-dead-47ee-857d-0235b942f608"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d0ef34d-b53b-4481-a461-7ffd51900697"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a95f450d-f4cc-408b-a212-c7a199da647a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6277f11d-fbf9-4398-b711-dfcedf065f03"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c5bbe94-6b0e-4605-b734-e0df13d25149"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa087c72-2928-4ea5-846d-946a71fc7aa7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""883d77be-4bc5-4c5a-a631-1de8ab6d3cc6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""641f4c4f-2fd9-4edd-988a-207258dd8af0"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cccf36fe-1029-4011-94d9-957c46891bb5"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c79f067-91dc-43c5-9749-a57d77445d98"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf06d85-1a65-4c70-8b59-5ad577c7ea6d"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a42f20e2-0c95-44a9-b78e-8ca3a8c050e8"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a0cc19c-3f8f-4dd0-a81b-3029ad1a9d50"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectOptionNextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""174af871-a383-428d-93e5-f1dec97669d7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectOptionNextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b4b9b30-b6a2-4aad-966a-20336174448d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d13bf652-bc00-4f5f-974b-47557cedf5ea"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenItemInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a3fca4-2aa8-4282-9013-dc71c54fb8f2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2420eef5-2c9b-416c-9d0f-01c3f69ef257"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Repair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main"",
            ""bindingGroup"": ""Main"",
            ""devices"": []
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Movement = m_Main.FindAction("Movement", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_Look = m_Main.FindAction("Look", throwIfNotFound: true);
        m_Main_Attack = m_Main.FindAction("Attack", throwIfNotFound: true);
        m_Main_Block = m_Main.FindAction("Block", throwIfNotFound: true);
        m_Main_Interact = m_Main.FindAction("Interact", throwIfNotFound: true);
        m_Main_Cast = m_Main.FindAction("Cast", throwIfNotFound: true);
        m_Main_Boost = m_Main.FindAction("Boost", throwIfNotFound: true);
        m_Main_Sheathe = m_Main.FindAction("Sheathe", throwIfNotFound: true);
        m_Main_Inventory = m_Main.FindAction("Inventory", throwIfNotFound: true);
        m_Main_EquipItem = m_Main.FindAction("EquipItem", throwIfNotFound: true);
        m_Main_OpenItemInfo = m_Main.FindAction("OpenItemInfo", throwIfNotFound: true);
        m_Main__1 = m_Main.FindAction("1", throwIfNotFound: true);
        m_Main__2 = m_Main.FindAction("2", throwIfNotFound: true);
        m_Main__3 = m_Main.FindAction("3", throwIfNotFound: true);
        m_Main__4 = m_Main.FindAction("4", throwIfNotFound: true);
        m_Main__5 = m_Main.FindAction("5", throwIfNotFound: true);
        m_Main__6 = m_Main.FindAction("6", throwIfNotFound: true);
        m_Main__7 = m_Main.FindAction("7", throwIfNotFound: true);
        m_Main__8 = m_Main.FindAction("8", throwIfNotFound: true);
        m_Main__9 = m_Main.FindAction("9", throwIfNotFound: true);
        m_Main_SelectOptionNextDialog = m_Main.FindAction("SelectOptionNextDialog", throwIfNotFound: true);
        m_Main_Repair = m_Main.FindAction("Repair", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Movement;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_Look;
    private readonly InputAction m_Main_Attack;
    private readonly InputAction m_Main_Block;
    private readonly InputAction m_Main_Interact;
    private readonly InputAction m_Main_Cast;
    private readonly InputAction m_Main_Boost;
    private readonly InputAction m_Main_Sheathe;
    private readonly InputAction m_Main_Inventory;
    private readonly InputAction m_Main_EquipItem;
    private readonly InputAction m_Main_OpenItemInfo;
    private readonly InputAction m_Main__1;
    private readonly InputAction m_Main__2;
    private readonly InputAction m_Main__3;
    private readonly InputAction m_Main__4;
    private readonly InputAction m_Main__5;
    private readonly InputAction m_Main__6;
    private readonly InputAction m_Main__7;
    private readonly InputAction m_Main__8;
    private readonly InputAction m_Main__9;
    private readonly InputAction m_Main_SelectOptionNextDialog;
    private readonly InputAction m_Main_Repair;
    public struct MainActions
    {
        private @PlayerInput m_Wrapper;
        public MainActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Main_Movement;
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @Look => m_Wrapper.m_Main_Look;
        public InputAction @Attack => m_Wrapper.m_Main_Attack;
        public InputAction @Block => m_Wrapper.m_Main_Block;
        public InputAction @Interact => m_Wrapper.m_Main_Interact;
        public InputAction @Cast => m_Wrapper.m_Main_Cast;
        public InputAction @Boost => m_Wrapper.m_Main_Boost;
        public InputAction @Sheathe => m_Wrapper.m_Main_Sheathe;
        public InputAction @Inventory => m_Wrapper.m_Main_Inventory;
        public InputAction @EquipItem => m_Wrapper.m_Main_EquipItem;
        public InputAction @OpenItemInfo => m_Wrapper.m_Main_OpenItemInfo;
        public InputAction @_1 => m_Wrapper.m_Main__1;
        public InputAction @_2 => m_Wrapper.m_Main__2;
        public InputAction @_3 => m_Wrapper.m_Main__3;
        public InputAction @_4 => m_Wrapper.m_Main__4;
        public InputAction @_5 => m_Wrapper.m_Main__5;
        public InputAction @_6 => m_Wrapper.m_Main__6;
        public InputAction @_7 => m_Wrapper.m_Main__7;
        public InputAction @_8 => m_Wrapper.m_Main__8;
        public InputAction @_9 => m_Wrapper.m_Main__9;
        public InputAction @SelectOptionNextDialog => m_Wrapper.m_Main_SelectOptionNextDialog;
        public InputAction @Repair => m_Wrapper.m_Main_Repair;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Attack.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Block.started -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Interact.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Cast.started -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Cast.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Cast.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Boost.started -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Sheathe.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @Sheathe.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @Sheathe.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @Inventory.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @EquipItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @EquipItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @EquipItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @OpenItemInfo.started -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @OpenItemInfo.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @OpenItemInfo.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @_1.started -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_1.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_1.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_2.started -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_2.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_2.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_3.started -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_3.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_3.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_4.started -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_4.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_4.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_5.started -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_5.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_5.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_6.started -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_6.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_6.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_7.started -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_7.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_7.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_8.started -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_8.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_8.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_9.started -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @_9.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @_9.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @SelectOptionNextDialog.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @Repair.started -= m_Wrapper.m_MainActionsCallbackInterface.OnRepair;
                @Repair.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnRepair;
                @Repair.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnRepair;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Cast.started += instance.OnCast;
                @Cast.performed += instance.OnCast;
                @Cast.canceled += instance.OnCast;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @Sheathe.started += instance.OnSheathe;
                @Sheathe.performed += instance.OnSheathe;
                @Sheathe.canceled += instance.OnSheathe;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @EquipItem.started += instance.OnEquipItem;
                @EquipItem.performed += instance.OnEquipItem;
                @EquipItem.canceled += instance.OnEquipItem;
                @OpenItemInfo.started += instance.OnOpenItemInfo;
                @OpenItemInfo.performed += instance.OnOpenItemInfo;
                @OpenItemInfo.canceled += instance.OnOpenItemInfo;
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
                @_3.started += instance.On_3;
                @_3.performed += instance.On_3;
                @_3.canceled += instance.On_3;
                @_4.started += instance.On_4;
                @_4.performed += instance.On_4;
                @_4.canceled += instance.On_4;
                @_5.started += instance.On_5;
                @_5.performed += instance.On_5;
                @_5.canceled += instance.On_5;
                @_6.started += instance.On_6;
                @_6.performed += instance.On_6;
                @_6.canceled += instance.On_6;
                @_7.started += instance.On_7;
                @_7.performed += instance.On_7;
                @_7.canceled += instance.On_7;
                @_8.started += instance.On_8;
                @_8.performed += instance.On_8;
                @_8.canceled += instance.On_8;
                @_9.started += instance.On_9;
                @_9.performed += instance.On_9;
                @_9.canceled += instance.On_9;
                @SelectOptionNextDialog.started += instance.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.performed += instance.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.canceled += instance.OnSelectOptionNextDialog;
                @Repair.started += instance.OnRepair;
                @Repair.performed += instance.OnRepair;
                @Repair.canceled += instance.OnRepair;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_MainSchemeIndex = -1;
    public InputControlScheme MainScheme
    {
        get
        {
            if (m_MainSchemeIndex == -1) m_MainSchemeIndex = asset.FindControlSchemeIndex("Main");
            return asset.controlSchemes[m_MainSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnCast(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnSheathe(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnEquipItem(InputAction.CallbackContext context);
        void OnOpenItemInfo(InputAction.CallbackContext context);
        void On_1(InputAction.CallbackContext context);
        void On_2(InputAction.CallbackContext context);
        void On_3(InputAction.CallbackContext context);
        void On_4(InputAction.CallbackContext context);
        void On_5(InputAction.CallbackContext context);
        void On_6(InputAction.CallbackContext context);
        void On_7(InputAction.CallbackContext context);
        void On_8(InputAction.CallbackContext context);
        void On_9(InputAction.CallbackContext context);
        void OnSelectOptionNextDialog(InputAction.CallbackContext context);
        void OnRepair(InputAction.CallbackContext context);
    }
}
