//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""cd93eaba-4f5e-4d45-b152-9afee2c7b8cb"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2503a44e-de01-494d-a849-f819ab1103a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""ScaleVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""93c06cbe-8f24-4b7d-acdb-eb72b4ed006e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""4f8bbe7d-fdff-4601-b38e-34a23a6800a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0ed6cbfe-8698-4dff-b5ff-5488d3e73074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""77623c41-5045-4db3-b681-679d417e986c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backstep"",
                    ""type"": ""Button"",
                    ""id"": ""bd269db9-f4d3-4ce0-ba78-a8565d8ab074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""59aa17fa-da05-41d5-8af2-ca2905f1fa8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cast"",
                    ""type"": ""Button"",
                    ""id"": ""5992dc29-9da7-45d1-93e8-1e0d210bd619"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""a1fbe459-1d27-4f07-8ae7-d53aa7bcb832"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sheathe"",
                    ""type"": ""Button"",
                    ""id"": ""c67c5b77-43e4-46e4-8d05-84d3e7aa816c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LanternToggle"",
                    ""type"": ""Button"",
                    ""id"": ""56de3467-bc06-41fe-98fc-66e804d608f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""81249db7-aa4b-4161-8d39-7bd647223b6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""53bfa57f-666c-4d8d-bb52-513106024b55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipItem"",
                    ""type"": ""Button"",
                    ""id"": ""7578e0f1-ba30-466e-be08-644de1bb8668"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenItemInfo"",
                    ""type"": ""Button"",
                    ""id"": ""ed1d1c00-a786-453f-9ae9-7ef4db002a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""68001a43-ed66-493d-b10d-5846c1895701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""546779c5-a26c-4c1d-bdbb-5cee53d389ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3"",
                    ""type"": ""Button"",
                    ""id"": ""9e5a0bea-04f1-4427-a9cc-d497b8c4ff22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4"",
                    ""type"": ""Button"",
                    ""id"": ""14243c9e-4781-40da-a2a1-0eb5b99a6fe2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""5"",
                    ""type"": ""Button"",
                    ""id"": ""f418368e-0932-4d91-a5db-d5ef4625e304"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""6"",
                    ""type"": ""Button"",
                    ""id"": ""e4007ace-d404-4657-9bf6-d8c25bd4d52d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""7"",
                    ""type"": ""Button"",
                    ""id"": ""4c1e8d38-f004-409b-92f5-b23d286e4661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""8"",
                    ""type"": ""Button"",
                    ""id"": ""bce6554d-c22a-49dc-823c-85df5bd0ae81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""9"",
                    ""type"": ""Button"",
                    ""id"": ""bf41153e-ab8b-469f-982e-4cadeb17fa31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectOptionNextDialog"",
                    ""type"": ""Button"",
                    ""id"": ""a5847640-7584-4685-b756-3cd97c44ba17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemQuickSelect"",
                    ""type"": ""Button"",
                    ""id"": ""b34ce2fe-1713-4629-bbd5-29f2ff90abcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySelectLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c880f61b-c6e5-4622-8a77-29f2f3384c12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySelectRight"",
                    ""type"": ""Button"",
                    ""id"": ""d7ca7718-cb64-4d8d-886d-8bb0b8f0b0fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""224bf969-e45d-4915-b170-4a8bf6c751f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventorySelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""1fc81643-1875-4739-9c3c-8c71c55a0482"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""f3e10ad2-1b89-4b33-a457-94baabcf4465"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryChangeTabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""3a727f65-fcc5-4fa5-a2f4-5587423fd5d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryChangeTabRight"",
                    ""type"": ""Button"",
                    ""id"": ""5cec262d-35a1-43ea-bc65-adb5330e7b6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartButton1"",
                    ""type"": ""Button"",
                    ""id"": ""c9e288ab-f47d-4b19-b332-29c41d8fb0e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartButton2"",
                    ""type"": ""Button"",
                    ""id"": ""3f7fb8e2-8bc9-43e5-ab07-910ba00e1883"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""539dcec5-4f20-4996-91ff-715bb47a2fe5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9059d33e-7ecf-41d5-a8ea-8744eba9d733"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f1dd73ba-6f52-4832-9419-4953a83bbf83"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f1243b97-0d4e-43ef-8d3d-011de4b45aa8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ace151be-e29c-466f-b336-bd8c268e6808"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""24ec051f-ec71-4ad0-ae5d-6acf930b04e4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ad306a0-9d9d-4cb8-8741-c2f4ccd1e35d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40336839-ab37-4c7b-8157-a5dabf1a2794"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ebc543-b827-4e1e-9b72-02ac0fb5ac52"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7751df1-1596-449b-8175-f08417c73025"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=15,y=15)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08d4175c-c961-428f-99ec-1aa63f4ba34b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c22df093-e7dd-442f-9574-52b7f049f09d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc20ae64-d349-43c4-a99d-b7044a921091"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c364cebf-98f1-4e7f-a363-5a9dfc36dbd0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b0f1b98-1ffc-44f9-b6c2-05f55b851337"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc42216-e67d-4fea-be1a-0cdae6c0dfeb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93c5f42a-dead-47ee-857d-0235b942f608"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb1ff23d-a678-4465-8680-d198b1ae7b3c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d0ef34d-b53b-4481-a461-7ffd51900697"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d11b247-ae2c-47ab-ad5d-908d9039da99"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a95f450d-f4cc-408b-a212-c7a199da647a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6277f11d-fbf9-4398-b711-dfcedf065f03"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c5bbe94-6b0e-4605-b734-e0df13d25149"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa087c72-2928-4ea5-846d-946a71fc7aa7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""883d77be-4bc5-4c5a-a631-1de8ab6d3cc6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""641f4c4f-2fd9-4edd-988a-207258dd8af0"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cccf36fe-1029-4011-94d9-957c46891bb5"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c79f067-91dc-43c5-9749-a57d77445d98"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf06d85-1a65-4c70-8b59-5ad577c7ea6d"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a42f20e2-0c95-44a9-b78e-8ca3a8c050e8"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""155a3b76-59c4-48b9-a7fd-6deae0b9cf50"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a0cc19c-3f8f-4dd0-a81b-3029ad1a9d50"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectOptionNextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""174af871-a383-428d-93e5-f1dec97669d7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectOptionNextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7441a8e2-36df-40ba-b068-1bcd496f713c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectOptionNextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b4b9b30-b6a2-4aad-966a-20336174448d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30040f40-1bb7-49ab-96b1-dd0e88424b32"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d13bf652-bc00-4f5f-974b-47557cedf5ea"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenItemInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89020a7a-03f9-416a-a456-4f8b06fac2c9"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenItemInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a3fca4-2aa8-4282-9013-dc71c54fb8f2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b86ac0d7-7544-4aac-88e7-cc2c911564dd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2420eef5-2c9b-416c-9d0f-01c3f69ef257"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemQuickSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6f33c09-3709-4548-977d-65047441ae71"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemQuickSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""660fc761-3dd0-4b83-a7d0-f41221860b34"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83f33cc9-4cf5-4401-bb73-38def9a1106b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91076dda-05d9-43a0-8dd0-df1069d783db"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c0df4eb-adc0-454f-9476-3be21d295258"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb0826b1-c284-40a9-a525-71cedaf3511a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd26f995-ea64-4a4b-aad1-23c12f5d3e7b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cbf642c-a244-42af-8319-abf781503d36"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70825d77-604f-46df-bbf9-4de033655d4c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a9a40d8-8fb5-4902-a475-28930458e042"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12c9597b-050a-47b3-9315-029aaee982bb"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd756e4b-d40c-407f-9562-4d41a3e57ec7"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19ab9640-7036-4b50-baa6-26c31e4e9a3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventorySelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dba75207-c5cb-4bc3-beb8-1363d49ff0f1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dff33ae4-c663-4659-b45f-7972215f960a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c6cb887-8931-42ae-8325-5bbf9a64fba0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryChangeTabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99e6b3d6-9b8a-4cfc-a6e5-669b97a71c94"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryChangeTabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""338041ee-fca7-4ba9-9593-0286725a770d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryChangeTabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a95543e-c95a-4f4e-bfd3-dfc4605b24f2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryChangeTabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfb2ca46-141f-4701-b263-12a273d3004e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8d7a2c-30d1-4c5d-b216-3260fce05ac8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ddbaf87-2ae0-4dd6-9ea4-e5676fba301d"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RestartButton1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02d145f1-0fb5-4750-b893-f5103bba6b5b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RestartButton2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be278f4b-2f92-43dc-8228-475e37d4f28f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backstep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2d4ff8b-993d-48a7-9519-aedb01781379"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backstep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main"",
            ""bindingGroup"": ""Main"",
            ""devices"": []
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Movement = m_Main.FindAction("Movement", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_Look = m_Main.FindAction("Look", throwIfNotFound: true);
        m_Main_Attack = m_Main.FindAction("Attack", throwIfNotFound: true);
        m_Main_Block = m_Main.FindAction("Block", throwIfNotFound: true);
        m_Main_Backstep = m_Main.FindAction("Backstep", throwIfNotFound: true);
        m_Main_Interact = m_Main.FindAction("Interact", throwIfNotFound: true);
        m_Main_Cast = m_Main.FindAction("Cast", throwIfNotFound: true);
        m_Main_Boost = m_Main.FindAction("Boost", throwIfNotFound: true);
        m_Main_Sheathe = m_Main.FindAction("Sheathe", throwIfNotFound: true);
        m_Main_LanternToggle = m_Main.FindAction("LanternToggle", throwIfNotFound: true);
        m_Main_Pause = m_Main.FindAction("Pause", throwIfNotFound: true);
        m_Main_Inventory = m_Main.FindAction("Inventory", throwIfNotFound: true);
        m_Main_EquipItem = m_Main.FindAction("EquipItem", throwIfNotFound: true);
        m_Main_OpenItemInfo = m_Main.FindAction("OpenItemInfo", throwIfNotFound: true);
        m_Main__1 = m_Main.FindAction("1", throwIfNotFound: true);
        m_Main__2 = m_Main.FindAction("2", throwIfNotFound: true);
        m_Main__3 = m_Main.FindAction("3", throwIfNotFound: true);
        m_Main__4 = m_Main.FindAction("4", throwIfNotFound: true);
        m_Main__5 = m_Main.FindAction("5", throwIfNotFound: true);
        m_Main__6 = m_Main.FindAction("6", throwIfNotFound: true);
        m_Main__7 = m_Main.FindAction("7", throwIfNotFound: true);
        m_Main__8 = m_Main.FindAction("8", throwIfNotFound: true);
        m_Main__9 = m_Main.FindAction("9", throwIfNotFound: true);
        m_Main_SelectOptionNextDialog = m_Main.FindAction("SelectOptionNextDialog", throwIfNotFound: true);
        m_Main_ItemQuickSelect = m_Main.FindAction("ItemQuickSelect", throwIfNotFound: true);
        m_Main_InventorySelectLeft = m_Main.FindAction("InventorySelectLeft", throwIfNotFound: true);
        m_Main_InventorySelectRight = m_Main.FindAction("InventorySelectRight", throwIfNotFound: true);
        m_Main_InventorySelectUp = m_Main.FindAction("InventorySelectUp", throwIfNotFound: true);
        m_Main_InventorySelectDown = m_Main.FindAction("InventorySelectDown", throwIfNotFound: true);
        m_Main_InventoryConfirm = m_Main.FindAction("InventoryConfirm", throwIfNotFound: true);
        m_Main_InventoryChangeTabLeft = m_Main.FindAction("InventoryChangeTabLeft", throwIfNotFound: true);
        m_Main_InventoryChangeTabRight = m_Main.FindAction("InventoryChangeTabRight", throwIfNotFound: true);
        m_Main_RestartButton1 = m_Main.FindAction("RestartButton1", throwIfNotFound: true);
        m_Main_RestartButton2 = m_Main.FindAction("RestartButton2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Movement;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_Look;
    private readonly InputAction m_Main_Attack;
    private readonly InputAction m_Main_Block;
    private readonly InputAction m_Main_Backstep;
    private readonly InputAction m_Main_Interact;
    private readonly InputAction m_Main_Cast;
    private readonly InputAction m_Main_Boost;
    private readonly InputAction m_Main_Sheathe;
    private readonly InputAction m_Main_LanternToggle;
    private readonly InputAction m_Main_Pause;
    private readonly InputAction m_Main_Inventory;
    private readonly InputAction m_Main_EquipItem;
    private readonly InputAction m_Main_OpenItemInfo;
    private readonly InputAction m_Main__1;
    private readonly InputAction m_Main__2;
    private readonly InputAction m_Main__3;
    private readonly InputAction m_Main__4;
    private readonly InputAction m_Main__5;
    private readonly InputAction m_Main__6;
    private readonly InputAction m_Main__7;
    private readonly InputAction m_Main__8;
    private readonly InputAction m_Main__9;
    private readonly InputAction m_Main_SelectOptionNextDialog;
    private readonly InputAction m_Main_ItemQuickSelect;
    private readonly InputAction m_Main_InventorySelectLeft;
    private readonly InputAction m_Main_InventorySelectRight;
    private readonly InputAction m_Main_InventorySelectUp;
    private readonly InputAction m_Main_InventorySelectDown;
    private readonly InputAction m_Main_InventoryConfirm;
    private readonly InputAction m_Main_InventoryChangeTabLeft;
    private readonly InputAction m_Main_InventoryChangeTabRight;
    private readonly InputAction m_Main_RestartButton1;
    private readonly InputAction m_Main_RestartButton2;
    public struct MainActions
    {
        private @PlayerInput m_Wrapper;
        public MainActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Main_Movement;
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @Look => m_Wrapper.m_Main_Look;
        public InputAction @Attack => m_Wrapper.m_Main_Attack;
        public InputAction @Block => m_Wrapper.m_Main_Block;
        public InputAction @Backstep => m_Wrapper.m_Main_Backstep;
        public InputAction @Interact => m_Wrapper.m_Main_Interact;
        public InputAction @Cast => m_Wrapper.m_Main_Cast;
        public InputAction @Boost => m_Wrapper.m_Main_Boost;
        public InputAction @Sheathe => m_Wrapper.m_Main_Sheathe;
        public InputAction @LanternToggle => m_Wrapper.m_Main_LanternToggle;
        public InputAction @Pause => m_Wrapper.m_Main_Pause;
        public InputAction @Inventory => m_Wrapper.m_Main_Inventory;
        public InputAction @EquipItem => m_Wrapper.m_Main_EquipItem;
        public InputAction @OpenItemInfo => m_Wrapper.m_Main_OpenItemInfo;
        public InputAction @_1 => m_Wrapper.m_Main__1;
        public InputAction @_2 => m_Wrapper.m_Main__2;
        public InputAction @_3 => m_Wrapper.m_Main__3;
        public InputAction @_4 => m_Wrapper.m_Main__4;
        public InputAction @_5 => m_Wrapper.m_Main__5;
        public InputAction @_6 => m_Wrapper.m_Main__6;
        public InputAction @_7 => m_Wrapper.m_Main__7;
        public InputAction @_8 => m_Wrapper.m_Main__8;
        public InputAction @_9 => m_Wrapper.m_Main__9;
        public InputAction @SelectOptionNextDialog => m_Wrapper.m_Main_SelectOptionNextDialog;
        public InputAction @ItemQuickSelect => m_Wrapper.m_Main_ItemQuickSelect;
        public InputAction @InventorySelectLeft => m_Wrapper.m_Main_InventorySelectLeft;
        public InputAction @InventorySelectRight => m_Wrapper.m_Main_InventorySelectRight;
        public InputAction @InventorySelectUp => m_Wrapper.m_Main_InventorySelectUp;
        public InputAction @InventorySelectDown => m_Wrapper.m_Main_InventorySelectDown;
        public InputAction @InventoryConfirm => m_Wrapper.m_Main_InventoryConfirm;
        public InputAction @InventoryChangeTabLeft => m_Wrapper.m_Main_InventoryChangeTabLeft;
        public InputAction @InventoryChangeTabRight => m_Wrapper.m_Main_InventoryChangeTabRight;
        public InputAction @RestartButton1 => m_Wrapper.m_Main_RestartButton1;
        public InputAction @RestartButton2 => m_Wrapper.m_Main_RestartButton2;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Attack.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAttack;
                @Block.started -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnBlock;
                @Backstep.started -= m_Wrapper.m_MainActionsCallbackInterface.OnBackstep;
                @Backstep.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnBackstep;
                @Backstep.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnBackstep;
                @Interact.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInteract;
                @Cast.started -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Cast.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Cast.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnCast;
                @Boost.started -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnBoost;
                @Sheathe.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @Sheathe.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @Sheathe.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSheathe;
                @LanternToggle.started -= m_Wrapper.m_MainActionsCallbackInterface.OnLanternToggle;
                @LanternToggle.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnLanternToggle;
                @LanternToggle.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnLanternToggle;
                @Pause.started -= m_Wrapper.m_MainActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnPause;
                @Inventory.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @EquipItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @EquipItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @EquipItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnEquipItem;
                @OpenItemInfo.started -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @OpenItemInfo.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @OpenItemInfo.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnOpenItemInfo;
                @_1.started -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_1.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_1.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_1;
                @_2.started -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_2.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_2.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_2;
                @_3.started -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_3.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_3.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_3;
                @_4.started -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_4.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_4.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_4;
                @_5.started -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_5.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_5.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_5;
                @_6.started -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_6.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_6.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_6;
                @_7.started -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_7.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_7.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_7;
                @_8.started -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_8.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_8.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_8;
                @_9.started -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @_9.performed -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @_9.canceled -= m_Wrapper.m_MainActionsCallbackInterface.On_9;
                @SelectOptionNextDialog.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSelectOptionNextDialog;
                @ItemQuickSelect.started -= m_Wrapper.m_MainActionsCallbackInterface.OnItemQuickSelect;
                @ItemQuickSelect.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnItemQuickSelect;
                @ItemQuickSelect.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnItemQuickSelect;
                @InventorySelectLeft.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectLeft;
                @InventorySelectLeft.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectLeft;
                @InventorySelectLeft.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectLeft;
                @InventorySelectRight.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectRight;
                @InventorySelectRight.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectRight;
                @InventorySelectRight.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectRight;
                @InventorySelectUp.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectUp;
                @InventorySelectUp.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectUp;
                @InventorySelectUp.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectUp;
                @InventorySelectDown.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectDown;
                @InventorySelectDown.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectDown;
                @InventorySelectDown.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventorySelectDown;
                @InventoryConfirm.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryConfirm;
                @InventoryConfirm.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryConfirm;
                @InventoryConfirm.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryConfirm;
                @InventoryChangeTabLeft.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabLeft;
                @InventoryChangeTabLeft.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabLeft;
                @InventoryChangeTabLeft.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabLeft;
                @InventoryChangeTabRight.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabRight;
                @InventoryChangeTabRight.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabRight;
                @InventoryChangeTabRight.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryChangeTabRight;
                @RestartButton1.started -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton1;
                @RestartButton1.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton1;
                @RestartButton1.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton1;
                @RestartButton2.started -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton2;
                @RestartButton2.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton2;
                @RestartButton2.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnRestartButton2;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @Backstep.started += instance.OnBackstep;
                @Backstep.performed += instance.OnBackstep;
                @Backstep.canceled += instance.OnBackstep;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Cast.started += instance.OnCast;
                @Cast.performed += instance.OnCast;
                @Cast.canceled += instance.OnCast;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @Sheathe.started += instance.OnSheathe;
                @Sheathe.performed += instance.OnSheathe;
                @Sheathe.canceled += instance.OnSheathe;
                @LanternToggle.started += instance.OnLanternToggle;
                @LanternToggle.performed += instance.OnLanternToggle;
                @LanternToggle.canceled += instance.OnLanternToggle;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @EquipItem.started += instance.OnEquipItem;
                @EquipItem.performed += instance.OnEquipItem;
                @EquipItem.canceled += instance.OnEquipItem;
                @OpenItemInfo.started += instance.OnOpenItemInfo;
                @OpenItemInfo.performed += instance.OnOpenItemInfo;
                @OpenItemInfo.canceled += instance.OnOpenItemInfo;
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
                @_3.started += instance.On_3;
                @_3.performed += instance.On_3;
                @_3.canceled += instance.On_3;
                @_4.started += instance.On_4;
                @_4.performed += instance.On_4;
                @_4.canceled += instance.On_4;
                @_5.started += instance.On_5;
                @_5.performed += instance.On_5;
                @_5.canceled += instance.On_5;
                @_6.started += instance.On_6;
                @_6.performed += instance.On_6;
                @_6.canceled += instance.On_6;
                @_7.started += instance.On_7;
                @_7.performed += instance.On_7;
                @_7.canceled += instance.On_7;
                @_8.started += instance.On_8;
                @_8.performed += instance.On_8;
                @_8.canceled += instance.On_8;
                @_9.started += instance.On_9;
                @_9.performed += instance.On_9;
                @_9.canceled += instance.On_9;
                @SelectOptionNextDialog.started += instance.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.performed += instance.OnSelectOptionNextDialog;
                @SelectOptionNextDialog.canceled += instance.OnSelectOptionNextDialog;
                @ItemQuickSelect.started += instance.OnItemQuickSelect;
                @ItemQuickSelect.performed += instance.OnItemQuickSelect;
                @ItemQuickSelect.canceled += instance.OnItemQuickSelect;
                @InventorySelectLeft.started += instance.OnInventorySelectLeft;
                @InventorySelectLeft.performed += instance.OnInventorySelectLeft;
                @InventorySelectLeft.canceled += instance.OnInventorySelectLeft;
                @InventorySelectRight.started += instance.OnInventorySelectRight;
                @InventorySelectRight.performed += instance.OnInventorySelectRight;
                @InventorySelectRight.canceled += instance.OnInventorySelectRight;
                @InventorySelectUp.started += instance.OnInventorySelectUp;
                @InventorySelectUp.performed += instance.OnInventorySelectUp;
                @InventorySelectUp.canceled += instance.OnInventorySelectUp;
                @InventorySelectDown.started += instance.OnInventorySelectDown;
                @InventorySelectDown.performed += instance.OnInventorySelectDown;
                @InventorySelectDown.canceled += instance.OnInventorySelectDown;
                @InventoryConfirm.started += instance.OnInventoryConfirm;
                @InventoryConfirm.performed += instance.OnInventoryConfirm;
                @InventoryConfirm.canceled += instance.OnInventoryConfirm;
                @InventoryChangeTabLeft.started += instance.OnInventoryChangeTabLeft;
                @InventoryChangeTabLeft.performed += instance.OnInventoryChangeTabLeft;
                @InventoryChangeTabLeft.canceled += instance.OnInventoryChangeTabLeft;
                @InventoryChangeTabRight.started += instance.OnInventoryChangeTabRight;
                @InventoryChangeTabRight.performed += instance.OnInventoryChangeTabRight;
                @InventoryChangeTabRight.canceled += instance.OnInventoryChangeTabRight;
                @RestartButton1.started += instance.OnRestartButton1;
                @RestartButton1.performed += instance.OnRestartButton1;
                @RestartButton1.canceled += instance.OnRestartButton1;
                @RestartButton2.started += instance.OnRestartButton2;
                @RestartButton2.performed += instance.OnRestartButton2;
                @RestartButton2.canceled += instance.OnRestartButton2;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_MainSchemeIndex = -1;
    public InputControlScheme MainScheme
    {
        get
        {
            if (m_MainSchemeIndex == -1) m_MainSchemeIndex = asset.FindControlSchemeIndex("Main");
            return asset.controlSchemes[m_MainSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnBackstep(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnCast(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnSheathe(InputAction.CallbackContext context);
        void OnLanternToggle(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnEquipItem(InputAction.CallbackContext context);
        void OnOpenItemInfo(InputAction.CallbackContext context);
        void On_1(InputAction.CallbackContext context);
        void On_2(InputAction.CallbackContext context);
        void On_3(InputAction.CallbackContext context);
        void On_4(InputAction.CallbackContext context);
        void On_5(InputAction.CallbackContext context);
        void On_6(InputAction.CallbackContext context);
        void On_7(InputAction.CallbackContext context);
        void On_8(InputAction.CallbackContext context);
        void On_9(InputAction.CallbackContext context);
        void OnSelectOptionNextDialog(InputAction.CallbackContext context);
        void OnItemQuickSelect(InputAction.CallbackContext context);
        void OnInventorySelectLeft(InputAction.CallbackContext context);
        void OnInventorySelectRight(InputAction.CallbackContext context);
        void OnInventorySelectUp(InputAction.CallbackContext context);
        void OnInventorySelectDown(InputAction.CallbackContext context);
        void OnInventoryConfirm(InputAction.CallbackContext context);
        void OnInventoryChangeTabLeft(InputAction.CallbackContext context);
        void OnInventoryChangeTabRight(InputAction.CallbackContext context);
        void OnRestartButton1(InputAction.CallbackContext context);
        void OnRestartButton2(InputAction.CallbackContext context);
    }
}
